WIDTH = 10
HEIGHT = 20
SCALE = 30
FPS = 60

SCORE_COLOR = 'white'
SCREEN_COLOR = 'black'
SNAKE_COLOR = 'yellow'
GAME_OVER_COLOR = 'red'
APPLE_COLOR = 'red'

ELEMENT_SIZE = 28
ELEMENT_RADIUS = 3

INITIAL_SPEED_DELAY = FPS // 2